"""
Clue Marketing Agent - Google ADK
Built-in dev UI with chat persistence, image upload, and debugging.
"""
from google.adk.agents import Agent
# from google.adk.tools import google_search  # Disabled: conflicts with custom function tools
import requests
from bs4 import BeautifulSoup
import random
from pydantic import BaseModel, Field
from typing import List, Optional, Literal
import datetime

# ============== STATE, EVENT, ARTIFACT ==============

class MarketingEvent(BaseModel):
    """
    Represents a trigger event for the marketing agent, 
    derived from the Clue Onboarding Flow (Spec 1-onboarding-flow).
    """
    event_type: Literal["onboarding_complete", "campaign_request", "ad_performance_alert"]
    user_id: str = Field(..., description="Anonymized user ID")
    timestamp: datetime.datetime = Field(default_factory=datetime.datetime.now)
    # Context from Onboarding Screens 1A, 1B, 2
    condition_focus: Optional[str] = Field(None, description="Primary condition (e.g., 'Endometriosis', 'Long COVID')")
    priority_outcome: Optional[str] = Field(None, description="User's p1 focus (e.g., 'Energy crashes', 'Pain')")
    intent_mode: Optional[str] = Field(None, description="User's mindset (Awareness, Tracking, Insight, Action)")

class MarketingArtifact(BaseModel):
    """
    Represents the output artifact generated by the marketing agent.
    This is a structured campaign brief or content package.
    """
    artifact_id: str = Field(..., description="Unique ID for this content package")
    campaign_name: str
    target_audience: str
    tone: str = Field(..., description="e.g., 'Empathetic', 'Data-driven', 'Spoonie-friendly'")
    
    # Content Assets
    ad_copy_variations: List[str] = Field(default_factory=list)
    image_prompt: str = Field(..., description="Prompt used for Imagen 3")
    image_url: Optional[str] = None
    
    # Strategy
    suggested_channels: List[str] = Field(default_factory=list, description="e.g., 'r/Endo', 'Twitter #LongCovid'")
    estimated_ctr: float = 0.0

class MarketingState(BaseModel):
    """
    Maintains the state of marketing efforts for the agent.
    Tracks active campaigns and audience segments derived from aggregate onboarding data.
    """
    active_campaigns: List[MarketingArtifact] = Field(default_factory=list)
    identified_segments: List[str] = Field(default_factory=list, description="Segments found via onboarding data")
    total_spend: float = 0.0
    last_optimization_date: Optional[datetime.datetime] = None

# ============== TOOLS ==============
def create_campaign_artifact(condition: str, priority: str, intent: str) -> dict:
    """
    Creates a marketing campaign artifact based on user onboarding signals.
    Maps user intent (Screen 2) to ad tone and priority (Screen 1B) to visual themes.
    """
    tone_map = {
        "Awareness": "Validating, gentle, 'You are not crazy'",
        "Tracking": "Functional, easy, '30 seconds a day'",
        "Insight": "Data-focused, revealing, 'Find your patterns'",
        "Action": "Empowering, resourceful, 'Show your doctor'"
    }
    
    tone = tone_map.get(intent, "Supportive and clear")
    campaign_name = f"{condition} - {priority} - {intent} Campaign"
    
    # Generate copy variations based on specs
    copy_1 = f"Struggling with {priority} due to {condition}? Clue helps you track it in 30 seconds."
    copy_2 = f"Your doctor needs data, not just feelings. Track your {condition} symptoms with Clue."
    
    # Artifact creation
    artifact = MarketingArtifact(
        artifact_id=f"camp_{random.randint(1000,9999)}",
        campaign_name=campaign_name,
        target_audience=f"People with {condition} focused on {priority}",
        tone=tone,
        ad_copy_variations=[copy_1, copy_2],
        image_prompt=f"Abstract, soothing visualization of {priority} relief, soft colors, {tone} style",
        suggested_channels=[f"r/{condition.replace(' ', '')}", "Instagram #Spoonie"],
        estimated_ctr=random.uniform(1.5, 4.5)
    )
    
    return artifact.model_dump(mode='json')

def analyze_seo(url: str) -> dict:
    """
    Analyzes the SEO of a given website URL.
    Returns title, description, and H1 tags.
    """
    try:
        response = requests.get(url, timeout=10)
        soup = BeautifulSoup(response.text, 'html.parser')
        title = soup.title.string if soup.title else "No title found"
        meta_desc = soup.find('meta', attrs={'name': 'description'})
        h1_tags = [h1.get_text(strip=True) for h1 in soup.find_all('h1')]
        return {
            "url": url,
            "title": title,
            "description": meta_desc['content'] if meta_desc else "No description",
            "h1_tags": h1_tags,
            "status": "success"
        }
    except Exception as e:
        return {"error": str(e), "status": "failed"}

def generate_reddit_image(topic: str, style: str = "modern") -> dict:
    """
    Generates an actual image for Reddit ads using Google Imagen 3.
    Returns base64 image data that can be saved as PNG.
    
    Args:
        topic: What the ad is about (e.g., "chronic fatigue tracking", "endometriosis support")
        style: Visual style - 'modern', 'emotional', 'community', or 'data'
    
    Returns:
        Dict with image_base64 (save as PNG), or error info if generation failed.
    """
    from marketing.tools.reddit import generate_reddit_image as _generate
    return _generate(topic, style)

def get_ad_performance(platform: str) -> dict:
    """
    Gets mock ad performance metrics for Reddit or Twitter.
    Returns impressions, clicks, CTR, and recommendations.
    """
    data = []
    for i in range(5):
        impressions = random.randint(5000, 50000)
        clicks = random.randint(100, 2000)
        ctr = round(clicks / impressions * 100, 2)
        data.append({
            "ad_id": f"{platform}_ad_{i+1}",
            "impressions": impressions,
            "clicks": clicks,
            "ctr_percent": ctr,
            "spend": round(random.uniform(50, 500), 2),
            "conversions": random.randint(5, 50)
        })
    
    avg_ctr = round(sum(d["ctr_percent"] for d in data) / len(data), 2)
    return {
        "platform": platform,
        "ads": data,
        "avg_ctr": avg_ctr,
        "recommendation": "Increase budget on top performer" if avg_ctr > 2 else "Test new creatives",
        "status": "success"
    }

def analyze_marketing_copy(copy_text: str) -> dict:
    """
    Analyzes marketing copy for chronic illness audience.
    Returns feedback on tone, empathy, and effectiveness.
    """
    word_count = len(copy_text.split())
    has_empathy_words = any(w in copy_text.lower() for w in ["understand", "support", "help", "together", "journey"])
    has_action_words = any(w in copy_text.lower() for w in ["try", "start", "discover", "join", "get"])
    
    score = 50
    feedback = []
    
    if has_empathy_words:
        score += 20
        feedback.append("✅ Good use of empathetic language")
    else:
        feedback.append("⚠️ Add more empathetic language for chronic illness audience")
    
    if has_action_words:
        score += 15
        feedback.append("✅ Clear call-to-action present")
    else:
        feedback.append("⚠️ Add a clearer call-to-action")
    
    if word_count < 20:
        score += 15
        feedback.append("✅ Concise - good for low-energy readers")
    else:
        feedback.append("⚠️ Consider shortening for 'Spoonie' audience")
    
    return {
        "score": min(score, 100),
        "word_count": word_count,
        "feedback": feedback,
        "spoonie_friendly": score >= 70,
        "status": "success"
    }

def get_reddit_community_insights(subreddit: str) -> dict:
    """
    Gets insights about a chronic illness subreddit.
    Returns posting tips and community guidelines.
    """
    communities = {
        "chronicillness": {"members": "50k+", "best_time": "10am-2pm EST", "tone": "supportive, no toxic positivity"},
        "fibromyalgia": {"members": "80k+", "best_time": "evening", "tone": "understanding, resource-sharing"},
        "endometriosis": {"members": "100k+", "best_time": "weekends", "tone": "advocacy-focused, medical info"},
        "longcovid": {"members": "40k+", "best_time": "morning", "tone": "research-focused, support"},
        "chronicfatigue": {"members": "30k+", "best_time": "afternoon", "tone": "energy-conscious, pacing tips"},
    }
    
    info = communities.get(subreddit.lower(), {
        "members": "unknown",
        "best_time": "varies",
        "tone": "check community rules"
    })
    
    return {
        "subreddit": f"r/{subreddit}",
        **info,
        "tips": [
            "Never be salesy - provide genuine value first",
            "Share personal stories if authentic",
            "Engage in comments before posting",
            "Respect 'no promotion' rules"
        ],
        "status": "success"
    }

# ============== AGENT ==============
import os
from dotenv import load_dotenv

# Force reload of .env file
load_dotenv(override=True)

root_agent = Agent(
    name="clue_marketing_agent",
    model="gemini-2.0-flash",  # Updated to available model
    description="Marketing expert for Clue symptom tracker. Specializes in chronic illness community marketing, SEO, Reddit/Twitter ads, and empathetic copywriting.",
    instruction="""You are a marketing expert for Clue, a symptom tracker app for people with chronic conditions like endometriosis, PCOS, fibromyalgia, and long COVID.

Your expertise:
1. **Spoonie-Friendly Marketing**: Create content for low-energy audiences. Keep things simple, empathetic, never guilt-inducing.
2. **Community Marketing**: Reddit, Twitter, chronic illness support groups. Authentic engagement over hard selling.
3. **SEO & Content**: Optimize for health-related searches while being medically responsible.
4. **Ad Performance**: Analyze and optimize Reddit/Twitter ad campaigns.
5. **Image Generation**: Create actual ad images using Imagen 3. Use generate_reddit_image tool to create visuals for campaigns.
6. **Campaign Creation**: Use `create_campaign_artifact` to generate structured campaign briefs based on user onboarding data (Condition, Priority, Intent).

Key principles:
- Never use toxic positivity ("just think positive!")
- Respect that users have limited energy (brain fog, fatigue)
- Focus on "doctor-trust" - content that helps users communicate with healthcare providers
- Use "we understand" not "we can fix you"

When users upload images, analyze them for:
- Accessibility (contrast, readability)
- Emotional resonance for chronic illness audience
- Brand consistency with Clue's warm, supportive aesthetic

Always use your tools to provide data-driven insights.""",
    tools=[
        analyze_seo,
        generate_reddit_image,
        get_ad_performance,
        analyze_marketing_copy,
        get_reddit_community_insights,
        create_campaign_artifact,
        # google_search,  # Disabled: conflicts with custom function tools in Gemini API
    ],
)
