/**
 * TypeScript interfaces for the Onboarding Agent
 *
 * Why this exists: Defines the shape of user context data, generated output,
 * and stored conversion context for both pre-conversion (WatchListPreview)
 * and post-conversion (Clue Agent personalization) flows.
 */

// =============================================================================
// INPUT: User Journey Context (assembled from multiple sources)
// =============================================================================

/**
 * UTM parameters from the ad campaign that brought the user
 * Why: Tells us which messaging already resonated with them
 */
export interface UTMContext {
  source: string | null; // 'reddit', 'google', etc.
  medium: string | null; // 'paid', 'organic', etc.
  campaign: string | null; // 'prediction_depth_test', etc.
  content: string | null; // 'flare_forecast', 'top_suspect', etc.
  term: string | null; // keyword if any
}

/**
 * Ad copy that brought the user to the site
 * Why: We should echo language they already clicked on
 */
export interface AdContext {
  headline: string; // "Your flares have a forecast"
  description: string; // "A symptom tracker that learns your patterns..."
  cta: string; // "See your forecast"
  adGroup: string; // "flare_forecast"
  altHeadlines: string[]; // Alternative headlines tested
  targetSubreddits: string[]; // Where ad was shown (e.g., ["r/ChronicIllness", "r/Fibromyalgia"])
}

/**
 * Landing page copy the user saw
 * Why: Continuity - repeat the value props they read
 */
export interface LandingPageContext {
  productOffering: string; // 'flare-forecast', 'top-suspect', etc.
  heroTitle: string; // "Predict your next flare"
  heroSubtitle: string; // "See the storm coming..."
  primaryCTA: string; // "Start predicting flares"
  empathyCopy: string; // "A shift in your patterns suggests..."
  focusFeature: string; // "Lag Effect Detection (24-48h warning)"
  headlineVariants: Record<string, { h1: string; h2: string }>; // A/B test variants
}

/**
 * Persona story (NOT name - internal language)
 * Why: Social proof - "someone like me uses this"
 */
export interface PersonaContext {
  story: string; // "She manages fibromyalgia and long COVID..."
  description: string; // "Project manager who had to step back..."
  // NOTE: We deliberately exclude name, age, demographic
}

/**
 * A single modal question response
 */
export interface QuestionAnswer {
  questionKey: string; // 'q1_entry', 'q2_pain_point', etc.
  questionText: string; // "What brings you here today?"
  answerValue: string; // 'fatigue', 'delayed_payback', etc.
  answerLabel: string; // "Fatigue that won't quit"
}

/**
 * All four modal question responses
 * Why: This is the user's self-declared intent and pain
 */
export interface ModalResponses {
  q1: QuestionAnswer; // Entry point - what condition/symptom
  q2: QuestionAnswer; // Pain point - what's hardest
  q3: QuestionAnswer; // Product-specific question 1
  q4: QuestionAnswer; // Product-specific question 2 (desired outcome)
}

/**
 * Complete user journey context for onboarding agent
 * This is EVERYTHING we know about the user at conversion time
 */
export interface UserConversionContext {
  // Session identifiers
  sessionId: string;
  modalSessionId: string;

  // Campaign attribution
  utm: UTMContext;

  // What they saw before clicking
  ad: AdContext | null; // null if direct visit

  // Landing page they arrived on
  landingPage: LandingPageContext;

  // Persona they connected with (story only, not name)
  persona: PersonaContext;

  // Their answers to modal questions
  answers: ModalResponses;

  // Device context (for copy adjustments)
  deviceType: 'mobile' | 'tablet' | 'desktop';
}

// =============================================================================
// OUTPUT: Generated Copy (from Gemini)
// =============================================================================

/**
 * Copy generated by Gemini for WatchListPreview
 * Why: Personalized messaging that speaks to their specific pain/desire
 */
export interface GeneratedCopy {
  /**
   * Headline that speaks directly to their pain/desire
   * Should reference their Q1 (condition) and Q2 (pain point)
   * Example: "We'll warn you 48 hours before your fatigue crashes"
   */
  headline: string;

  /**
   * Three "Watching for:" items personalized to their condition
   * Based on Q1 selection and product offering
   */
  watchItems: [string, string, string];

  /**
   * CTA text - MUST be first person
   * Example: "Save my progress", "Know my flare", "Start my forecast"
   */
  ctaText: string;
}

// =============================================================================
// OUTPUT: WatchListPreview Data
// =============================================================================

/**
 * Flare risk data for 7-day preview graph
 * Why: Shows users what predictions COULD look like (fake data in onboarding)
 */
export interface FlareRiskData {
  days: {
    date: string; // "Mon", "Tue", etc.
    risk: 'low' | 'elevated' | 'high';
    value: number; // 0-100 for chart
  }[];
}

/**
 * Symptom pattern data based on Q1 condition
 * Why: Shows personalized pattern visualization
 */
export interface PatternData {
  condition: string; // "fatigue", "migraines", etc.
  patternType: 'energy' | 'pain' | 'migraine' | 'gut';
  values: number[]; // 7 values for week visualization
  insight: string; // "Your energy tends to dip mid-week"
}

/**
 * Medication timing optimization preview
 * Why: Shows potential optimization (relevant for some users)
 */
export interface TimingData {
  items: {
    name: string; // "Morning meds"
    currentTime: string; // "7:00 AM"
    suggestedTime: string; // "6:30 AM"
    reason: string; // "Better absorption"
  }[];
}

/**
 * Complete data for WatchListPreview component
 */
export interface WatchListPreviewData {
  // Personalized headline (no subtitle)
  headline: string;

  // "Watching for:" items (3 personalized to Q1-Q4)
  watchItems: [string, string, string];

  // Graph data (fake preview)
  graphs: {
    flareRisk: FlareRiskData;
    symptomPatterns: PatternData;
    medicationTiming: TimingData;
  };

  // CTA (first person)
  cta: {
    text: string;
    action: 'google_signin';
  };

  // Status text
  statusText: string; // "First insight in ~3 days"
}

// =============================================================================
// STORED: Conversion Context (for Clue Agent)
// =============================================================================

/**
 * Promise category - what type of value we promised
 * Why: Helps Clue Agent know what to deliver first
 */
export type PromiseCategory =
  | 'prediction' // Flare forecast, early warning
  | 'trigger_discovery' // Find what's causing symptoms
  | 'validation' // Doctor-ready proof
  | 'pattern_finding'; // General pattern detection

/**
 * Stored conversion context for post-signup personalization
 * Why: Clue Agent asks "Why did this user sign up?" to personalize experience
 */
export interface StoredConversionContext {
  // User identifier (linked after Google sign-in)
  userId: string;
  modalSessionId: string;

  // Attribution
  utmSource: string | null;
  utmCampaign: string | null;
  utmContent: string | null;
  adHeadline: string | null;
  landingPage: string;

  // User's stated needs (Q1-Q4)
  conditionPrimary: string; // Q1 value: "fatigue"
  conditionLabel: string; // Q1 label: "Fatigue that won't quit"
  painPoint: string; // Q2 value
  painPointLabel: string; // Q2 label
  productNeed: string | null; // Q3 answer
  desiredOutcome: string | null; // Q4 answer

  // The promise we made (generated copy that converted them)
  generatedHeadline: string;
  generatedWatchItems: string[];
  generatedCta: string;

  // Promise category for tracking
  promiseCategory: PromiseCategory;

  // Conversion metadata
  convertedAt: Date;
  conversionMethod: 'google_signin' | 'email_create';
}

/**
 * Response format for Clue Agent's "Why did they sign up?" query
 */
export interface ConversionContextResponse {
  // What brought them
  source: {
    adHeadline: string | null;
    landingPage: string;
    utmCampaign: string | null;
  };

  // What they're managing
  condition: {
    primary: string; // "Fatigue that won't quit"
    painPoint: string; // "I pay for today's effort tomorrow"
  };

  // What they want
  desiredOutcome: string;

  // The promise we made (that converted them)
  promiseMade: {
    headline: string;
    watchItems: string[];
    ctaClicked: string;
  };

  // Promise category
  promiseCategory: PromiseCategory;

  // For first-run personalization
  suggestedFirstMessage: string;
}

// =============================================================================
// WIDGET CONTEXT (Q3 widget definition from onboarding-flow.json)
// =============================================================================

/**
 * Q3 widget context from onboarding-flow.json
 * Why: The widget determines what data we capture and what promise we make
 */
export interface WidgetContext {
  widgetId: string; // "w1_time_of_day_energy"
  widgetName: string; // "Time-of-Day Energy Map"
  widgetType: string; // "time_segment_selector", "dual_selector", etc.
  q4Value: string; // "We will learn your energy rhythm and predict your best windows"
  captures: string[]; // ["daily_energy_pattern", "peak_energy_time"]
  userInput: {
    condition: string; // The condition selected in Q3
    widgetValue: number | string | string[]; // The value captured by the widget
  };
}

/**
 * Enhanced user context with widget data
 * Why: Provides full context including Q3 widget definition for personalization
 */
export interface EnhancedUserContext extends UserConversionContext {
  widget: WidgetContext;
}

// =============================================================================
// AI-GENERATED UI (Layout Selection + Copy)
// =============================================================================

/**
 * Layout ID for domain-specific UI
 * Why: Each Q1 domain has a specialized layout that best represents the value prop
 */
export type LayoutId =
  | 'fatigue' // Energy timeline, crash prevention focus
  | 'flares' // 7-day forecast, early warning focus
  | 'migraines' // Trigger correlation (weather, food, cycle)
  | 'ibs_gut' // Food-symptom timeline
  | 'multiple' // Multi-symptom dashboard
  | 'other'; // Pattern discovery

/**
 * AI-generated UI selection and copy
 * Why: The AI both selects the layout AND generates personalized copy
 */
export interface AIGeneratedUI {
  layoutId: LayoutId;
  headline: string; // Personalized to Q2 pain point
  watchItems: [string, string, string]; // Three monitoring promises
  ctaText: string; // First-person CTA ("Save my progress")
  victoryMessage: string; // Short celebration acknowledging Q3 input
  previewBadge: string; // Preview card badge/title (e.g., "YOUR ENERGY PATTERN", "FOOD-SYMPTOM TIMELINE")
}

// =============================================================================
// VICTORY COMPONENT (Combined celebration moment)
// =============================================================================

/**
 * Baseline data captured from Q3 widget
 * Why: Shows the user their "Day 1" data point as proof of progress
 */
export interface BaselineData {
  label: string; // "Energy right now", "Flare status", etc.
  value: string | number; // "50%", "Morning", etc.
  condition: string; // "ME/CFS", "Fibromyalgia", etc.
  widgetType: string; // For rendering the right visualization
}

/**
 * Promise card data
 * Why: Reinforces the value prop with personalized promises
 */
export interface PromiseData {
  headline: string; // AI-generated headline
  q4Value: string; // Widget's q4_value promise
  watchItems: string[]; // AI-generated watch items
}

/**
 * Victory component props
 * Why: Combined celebration showing progress + baseline + promise
 */
export interface VictoryProps {
  // Progress celebration
  stepsCompleted: number;
  totalSteps: number;

  // Baseline captured (Q3 data)
  baselineData: BaselineData;

  // Promise card (q4_value + AI copy)
  promise: PromiseData;

  // AI-generated victory message
  victoryMessage: string;
}

// =============================================================================
// SELECTED QUOTE (AI-selected testimonial for social proof)
// =============================================================================

/**
 * AI-selected quote for social proof at top of ValuePropScreen
 * Why: Immediately establishes emotional connection with user by showing
 * a testimonial from someone with similar condition/pain point
 */
export interface SelectedQuote {
  /** The testimonial quote text */
  quote: string;
  /** Source attribution (e.g., "r/ChronicIllness", "Clue user") */
  source: string;
  /** Condition tag (e.g., "Long COVID", "POTS") */
  condition?: string;
  /** Whether this is a Clue insight (positive/solution-focused) */
  isClueInsight?: boolean;
}

// =============================================================================
// VALUE PROP SCREEN DATA (Complete screen data)
// =============================================================================

/**
 * Complete data for ValuePropScreen component
 * Why: Everything needed to render the dynamic sign-up screen
 */
export interface ValuePropScreenData {
  // Layout selection
  layoutId: LayoutId;

  // AI-selected social proof quote (shown at top)
  socialProofQuote: SelectedQuote;

  // Victory section
  victory: VictoryProps;

  // Preview section (domain-specific graph + watch items)
  preview: {
    headline: string;
    watchItems: [string, string, string];
    graphData: FlareRiskData | PatternData; // Layout-specific
    badge: string; // Preview card badge/title (e.g., "YOUR ENERGY PATTERN")
  };

  // CTA
  cta: {
    text: string;
    action: 'google_signin';
  };

  // Status
  statusText: string;
}

// =============================================================================
// GENERATION METADATA
// =============================================================================

/**
 * Metadata about the copy generation
 */
export interface GenerationMetadata {
  modelUsed: string; // 'gemini-3-flash-preview', 'gpt-4o-mini', etc.
  promptTemplateId: string;
  tokensUsed: number;
  latencyMs: number;
}

/**
 * Full result from copy generation
 */
export interface CopyGenerationResult {
  copy: GeneratedCopy;
  metadata: GenerationMetadata;
}

/**
 * Full result from AI UI generation (copy + layout selection)
 */
export interface AIGenerationResult {
  ui: AIGeneratedUI;
  metadata: GenerationMetadata;
}
