/**
 * Chat Agent LoadContext Node
 *
 * Why this exists: Hydrates the new Chat Agent with only the user context it
 * needs right before streaming: memories, graph summary, flare mode, and the
 * latest insight-owned clue.
 */

import { createClient, type SupabaseClient } from '@supabase/supabase-js';

import { getGraphSummary } from '@/backend/lib/graph';
import { getRelevantMemories } from '@/backend/lib/memory';

import type { ChatAgentStateType, ChatAgentStateUpdate, NextClue } from '../state';

/**
 * Minimal shape of the latest clue row fetched from Supabase.
 * Why this exists: The Chat Agent only needs the clue payload that is injected
 * into the system prompt, not the full insights record.
 */
interface InsightRow {
  content: string | null;
  reasoning: string | null;
  priority: number | null;
}

/**
 * Creates a privileged Supabase client for server-side context reads.
 * Why this exists: The Chat Agent runs inside the API route and needs direct
 * access to user-specific insights and preference rows.
 */
function getSupabase(): SupabaseClient {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
}

/**
 * Fetches the most recent active clue generated by the Insight Agent.
 * Why this exists: The clue is the contract between the Insight Agent and the
 * Chat Agent for the next best follow-up question.
 */
async function getLatestClue(
  supabase: SupabaseClient,
  userId: string
): Promise<NextClue | null> {
  const { data, error } = await supabase
    .from('insights')
    .select('content, reasoning, priority')
    .eq('user_id', userId)
    .eq('type', 'next_question')
    .neq('status', 'dismissed')
    .order('priority', { ascending: false })
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle<InsightRow>();

  if (error) {
    console.error('[chat-agent/load-context] Failed to load latest clue:', error);
    return null;
  }

  if (!data?.content) {
    return null;
  }

  return {
    question: data.content,
    reasoning:
      data.reasoning?.trim() ||
      'This clue was selected from the latest graph-based insight pass.',
    priority: data.priority ?? 0,
  };
}

/**
 * Loads the user context required to assemble the system prompt.
 * Why this exists: Keeps context reads centralized so the Chat Agent sees one
 * consistent snapshot of memories, graph state, preferences, and clue output.
 */
export async function loadContextNode(
  state: ChatAgentStateType
): Promise<ChatAgentStateUpdate> {
  const userId = state.userId;
  if (userId === 'anonymous') {
    return {
      memories: null,
      graphSummary: null,
      nextClue: null,
      isFlareMode: false,
    };
  }

  try {
    const supabase = getSupabase();

    const [memories, graphSummary, latestClue, preferencesResult] = await Promise.all([
      getRelevantMemories(userId, state.userMessageText),
      getGraphSummary(userId),
      getLatestClue(supabase, userId),
      supabase.from('user_preferences').select('flare_mode').eq('user_id', userId).maybeSingle(),
    ]);

    return {
      memories: memories || null,
      graphSummary: graphSummary || null,
      nextClue: latestClue,
      isFlareMode: preferencesResult.data?.flare_mode ?? false,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to load chat context';
    console.error('[chat-agent/load-context] Failed:', error);

    return {
      memories: null,
      graphSummary: null,
      nextClue: null,
      isFlareMode: false,
      errors: [message],
    };
  }
}
