/**
 * Chat Agent LoadContext Node
 *
 * Why this exists: Hydrates the new Chat Agent with only the user context it
 * needs right before streaming: memories, graph summary, flare mode, and the
 * latest insight-owned clue.
 */

import { createClient, type SupabaseClient } from '@supabase/supabase-js';

import { getGraphSummary, getLatestQueuedQuestionNode } from '@/backend/lib/graph';
import { getRelevantMemories } from '@/backend/lib/memory';

import type { ChatAgentStateType, ChatAgentStateUpdate, NextClue } from '../state';

/**
 * Minimal shape of the user preference row needed for turn pacing.
 * Why this exists: The Chat Agent only needs flare mode plus the queued
 * follow-up question handoff, not the full preferences record.
 */
interface UserPreferencesRow {
  flare_mode: boolean | null;
  pending_next_question: string | null;
}

/**
 * Creates a privileged Supabase client for server-side context reads.
 * Why this exists: The Chat Agent runs inside the API route and needs direct
 * access to user-specific insights and preference rows.
 */
function getSupabase(): SupabaseClient {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
}

/**
 * Fetches the most recent active clue generated by the Insight Agent.
 * Why this exists: The clue is the contract between the Insight Agent and the
 * Chat Agent for the next best follow-up question.
 */
async function getLatestClue(
  _supabase: SupabaseClient,
  userId: string
): Promise<NextClue | null> {
  const queuedNode = await getLatestQueuedQuestionNode(userId);
  if (!queuedNode?.questionText) {
    return null;
  }

  const nodeData = queuedNode.data as { reasoning?: unknown } | undefined;
  return {
    question: queuedNode.questionText,
    reasoning:
      (typeof nodeData?.reasoning === 'string' && nodeData.reasoning.trim()) ||
      'This clue was selected from the latest graph-based insight pass.',
    priority: queuedNode.questionPriority ?? 0,
  };
}

/**
 * Parses the queued next-question payload stored in user preferences.
 * Why this exists: The post-turn handoff stores a compact JSON string so the
 * next severity reply can consume the clue without racing the insight write.
 */
function parsePendingNextQuestion(value: string | null | undefined): NextClue | null {
  if (!value) {
    return null;
  }

  try {
    const parsed = JSON.parse(value) as Partial<NextClue> | null;
    if (!parsed?.question || typeof parsed.question !== 'string') {
      return null;
    }

    return {
      question: parsed.question,
      reasoning:
        typeof parsed.reasoning === 'string' && parsed.reasoning.trim()
          ? parsed.reasoning.trim()
          : 'This clue was queued while Clue finished collecting symptom severity.',
      priority: typeof parsed.priority === 'number' ? parsed.priority : 0,
    };
  } catch {
    return null;
  }
}

/**
 * Loads the user context required to assemble the system prompt.
 * Why this exists: Keeps context reads centralized so the Chat Agent sees one
 * consistent snapshot of memories, graph state, preferences, and clue output.
 */
export async function loadContextNode(
  state: ChatAgentStateType
): Promise<ChatAgentStateUpdate> {
  const userId = state.userId;
  if (userId === 'anonymous') {
    return {
      memories: null,
      graphSummary: null,
      nextClue: null,
      isFlareMode: false,
    };
  }

  try {
    const supabase = getSupabase();

    const [memories, graphSummary, latestClue, preferencesResult] = await Promise.all([
      getRelevantMemories(userId, state.userMessageText),
      getGraphSummary(userId),
      getLatestClue(supabase, userId),
      supabase
        .from('user_preferences')
        .select('flare_mode, pending_next_question')
        .eq('user_id', userId)
        .maybeSingle<UserPreferencesRow>(),
    ]);
    const queuedNextClue = parsePendingNextQuestion(preferencesResult.data?.pending_next_question);
    const shouldUseQueuedNextClue = Boolean(state.resolvedFollowupAction && queuedNextClue);

    return {
      memories: memories || null,
      graphSummary: graphSummary || null,
      nextClue: shouldUseQueuedNextClue ? queuedNextClue : latestClue,
      usedPendingNextClue: shouldUseQueuedNextClue,
      isFlareMode: preferencesResult.data?.flare_mode ?? false,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Failed to load chat context';
    console.error('[chat-agent/load-context] Failed:', error);

    return {
      memories: null,
      graphSummary: null,
      nextClue: null,
      usedPendingNextClue: false,
      isFlareMode: false,
      errors: [message],
    };
  }
}
