/**
 * TypeScript interfaces for the Onboarding Agent
 *
 * Why this exists: Defines the shape of user context data, generated output,
 * and stored conversion context for both pre-conversion (WatchListPreview)
 * and post-conversion (Clue Agent personalization) flows.
 */

// =============================================================================
// INPUT: User Journey Context (assembled from multiple sources)
// =============================================================================

/**
 * UTM parameters from the ad campaign that brought the user
 * Why: Tells us which messaging already resonated with them
 */
export interface UTMContext {
  source: string | null; // 'reddit', 'google', etc.
  medium: string | null; // 'paid', 'organic', etc.
  campaign: string | null; // 'prediction_depth_test', etc.
  content: string | null; // 'flare_forecast', 'top_suspect', etc.
  term: string | null; // keyword if any
}

/**
 * Ad copy that brought the user to the site
 * Why: We should echo language they already clicked on
 */
export interface AdContext {
  headline: string; // "Your flares have a forecast"
  description: string; // "A symptom tracker that learns your patterns..."
  cta: string; // "See your forecast"
  adGroup: string; // "flare_forecast"
}

/**
 * Landing page copy the user saw
 * Why: Continuity - repeat the value props they read
 */
export interface LandingPageContext {
  productOffering: string; // 'flare-forecast', 'top-suspect', etc.
  heroTitle: string; // "Predict your next flare"
  heroSubtitle: string; // "See the storm coming..."
  primaryCTA: string; // "Start predicting flares"
  empathyCopy: string; // "A shift in your patterns suggests..."
  focusFeature: string; // "Lag Effect Detection (24-48h warning)"
}

/**
 * Persona story (NOT name - internal language)
 * Why: Social proof - "someone like me uses this"
 */
export interface PersonaContext {
  story: string; // "She manages fibromyalgia and long COVID..."
  description: string; // "Project manager who had to step back..."
  // NOTE: We deliberately exclude name, age, demographic
}

/**
 * A single modal question response
 */
export interface QuestionAnswer {
  questionKey: string; // 'q1_entry', 'q2_pain_point', etc.
  questionText: string; // "What brings you here today?"
  answerValue: string; // 'fatigue', 'delayed_payback', etc.
  answerLabel: string; // "Fatigue that won't quit"
}

/**
 * All four modal question responses
 * Why: This is the user's self-declared intent and pain
 */
export interface ModalResponses {
  q1: QuestionAnswer; // Entry point - what condition/symptom
  q2: QuestionAnswer; // Pain point - what's hardest
  q3: QuestionAnswer; // Product-specific question 1
  q4: QuestionAnswer; // Product-specific question 2 (desired outcome)
}

/**
 * Complete user journey context for onboarding agent
 * This is EVERYTHING we know about the user at conversion time
 */
export interface UserConversionContext {
  // Session identifiers
  sessionId: string;
  modalSessionId: string;

  // Campaign attribution
  utm: UTMContext;

  // What they saw before clicking
  ad: AdContext | null; // null if direct visit

  // Landing page they arrived on
  landingPage: LandingPageContext;

  // Persona they connected with (story only, not name)
  persona: PersonaContext;

  // Their answers to modal questions
  answers: ModalResponses;

  // Device context (for copy adjustments)
  deviceType: 'mobile' | 'tablet' | 'desktop';
}

// =============================================================================
// OUTPUT: Generated Copy (from Gemini)
// =============================================================================

/**
 * Copy generated by Gemini for WatchListPreview
 * Why: Personalized messaging that speaks to their specific pain/desire
 */
export interface GeneratedCopy {
  /**
   * Headline that speaks directly to their pain/desire
   * Should reference their Q1 (condition) and Q2 (pain point)
   * Example: "We'll warn you 48 hours before your fatigue crashes"
   */
  headline: string;

  /**
   * Three "Watching for:" items personalized to their condition
   * Based on Q1 selection and product offering
   */
  watchItems: [string, string, string];

  /**
   * CTA text - MUST be first person
   * Example: "Save my progress", "Know my flare", "Start my forecast"
   */
  ctaText: string;
}

// =============================================================================
// OUTPUT: WatchListPreview Data
// =============================================================================

/**
 * Flare risk data for 7-day preview graph
 * Why: Shows users what predictions COULD look like (fake data in onboarding)
 */
export interface FlareRiskData {
  days: {
    date: string; // "Mon", "Tue", etc.
    risk: 'low' | 'elevated' | 'high';
    value: number; // 0-100 for chart
  }[];
}

/**
 * Symptom pattern data based on Q1 condition
 * Why: Shows personalized pattern visualization
 */
export interface PatternData {
  condition: string; // "fatigue", "migraines", etc.
  patternType: 'energy' | 'pain' | 'migraine' | 'gut';
  values: number[]; // 7 values for week visualization
  insight: string; // "Your energy tends to dip mid-week"
}

/**
 * Medication timing optimization preview
 * Why: Shows potential optimization (relevant for some users)
 */
export interface TimingData {
  items: {
    name: string; // "Morning meds"
    currentTime: string; // "7:00 AM"
    suggestedTime: string; // "6:30 AM"
    reason: string; // "Better absorption"
  }[];
}

/**
 * Complete data for WatchListPreview component
 */
export interface WatchListPreviewData {
  // Personalized headline (no subtitle)
  headline: string;

  // "Watching for:" items (3 personalized to Q1-Q4)
  watchItems: [string, string, string];

  // Graph data (fake preview)
  graphs: {
    flareRisk: FlareRiskData;
    symptomPatterns: PatternData;
    medicationTiming: TimingData;
  };

  // CTA (first person)
  cta: {
    text: string;
    action: 'google_signin';
  };

  // Status text
  statusText: string; // "First insight in ~3 days"
}

// =============================================================================
// STORED: Conversion Context (for Clue Agent)
// =============================================================================

/**
 * Promise category - what type of value we promised
 * Why: Helps Clue Agent know what to deliver first
 */
export type PromiseCategory =
  | 'prediction' // Flare forecast, early warning
  | 'trigger_discovery' // Find what's causing symptoms
  | 'validation' // Doctor-ready proof
  | 'pattern_finding'; // General pattern detection

/**
 * Stored conversion context for post-signup personalization
 * Why: Clue Agent asks "Why did this user sign up?" to personalize experience
 */
export interface StoredConversionContext {
  // User identifier (linked after Google sign-in)
  userId: string;
  modalSessionId: string;

  // Attribution
  utmSource: string | null;
  utmCampaign: string | null;
  utmContent: string | null;
  adHeadline: string | null;
  landingPage: string;

  // User's stated needs (Q1-Q4)
  conditionPrimary: string; // Q1 value: "fatigue"
  conditionLabel: string; // Q1 label: "Fatigue that won't quit"
  painPoint: string; // Q2 value
  painPointLabel: string; // Q2 label
  productNeed: string | null; // Q3 answer
  desiredOutcome: string | null; // Q4 answer

  // The promise we made (generated copy that converted them)
  generatedHeadline: string;
  generatedWatchItems: string[];
  generatedCta: string;

  // Promise category for tracking
  promiseCategory: PromiseCategory;

  // Conversion metadata
  convertedAt: Date;
  conversionMethod: 'google_signin' | 'email_create';
}

/**
 * Response format for Clue Agent's "Why did they sign up?" query
 */
export interface ConversionContextResponse {
  // What brought them
  source: {
    adHeadline: string | null;
    landingPage: string;
    utmCampaign: string | null;
  };

  // What they're managing
  condition: {
    primary: string; // "Fatigue that won't quit"
    painPoint: string; // "I pay for today's effort tomorrow"
  };

  // What they want
  desiredOutcome: string;

  // The promise we made (that converted them)
  promiseMade: {
    headline: string;
    watchItems: string[];
    ctaClicked: string;
  };

  // Promise category
  promiseCategory: PromiseCategory;

  // For first-run personalization
  suggestedFirstMessage: string;
}

// =============================================================================
// GENERATION METADATA
// =============================================================================

/**
 * Metadata about the copy generation
 */
export interface GenerationMetadata {
  modelUsed: string; // 'gemini-1.5-flash', 'gpt-4o-mini', etc.
  promptTemplateId: string;
  tokensUsed: number;
  latencyMs: number;
}

/**
 * Full result from copy generation
 */
export interface CopyGenerationResult {
  copy: GeneratedCopy;
  metadata: GenerationMetadata;
}
